apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
stringData:
  accessKeyID: "<AWS_ACCESS_KEY_ID>"
  secretAccessKey: "<AWS_SECRET_ACCESS_KEY>"

---
# DOC Driver
# https://github.com/ctrox/csi-s3
# Installazione driver
# kubectl apply -k "github.com/ctrox/csi-s3/deploy/kubernetes/base"

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-storage
provisioner: s3.csi.k8s.io
parameters:
  mounter: s3fs
  bucket: "nome-del-tuo-bucket"
  region: "eu-west-1"
  secretName: s3-secret
  secretNamespace: default
  # opzioni facoltative
  s3ForcePathStyle: "true"
  storage.kubernetes.io/csiProvisionerIdentity: "s3.csi.k8s.io"
reclaimPolicy: Retain
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-storage
  resources:
    requests:
      storage: 1Gi

---


apiVersion: v1
kind: Pod
metadata:
  name: s3-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo Hello from S3; sleep 3600; done"]
    volumeMounts:
    - name: s3-volume
      mountPath: /data
  volumes:
  - name: s3-volume
    persistentVolumeClaim:
      claimName: s3-pvc