apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testweb
  name: testweb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testweb
  template:
    metadata:
      labels:
        app: testweb
    spec:
      containers:
      - image: aminelli/spring-app-demo:1.1.0
        name: testweb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testweb
  name: testweb
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testweb
  type: ClusterIP
