apiVersion: v1
kind: Service
metadata:
  name: nodeport-whoami
  namespace: default
spec:
  selector:
    app: whoami
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80

    