apiVersion: v1
kind: Pod
metadata:
  name: k8sutils
  namespace: default
spec:
  containers:
  - name: k8sutils
    image: aminelli/k8sutils:debian12
    command:
    - sleep
    - "infinity"
  restartPolicy: Always
  