
apiVersion: v1
kind: Secret
metadata:
  name: java-ca-secret
  namespace: default
type: Opaque
data:
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3pEbmxKeWJYY2xyck0KS2VRMUpXRWMzVWw5MGhFeS9QVFh5YmtZSDdUeUlXZDY0dmszU3RSK1loSlZtdnF0RlltckVhS0kzVFNZb013MApoRmVOVUdMdkg0NktGd0VpSC8vbkQ5UXd5NUZ6VjFYRGRocXo5WXlvZmFvS3pvN3RjSTc2MzBreWE5d0hlT2lOCllKcFBycUgrNGdJSTdHTk1aaXNRRU0vNGlPYUdnT0ROc0ptajNscmZFUGtZWUk5aTI3ZzY3Y1NtNmQrWjVpTUgKTHJ6a1FXMG5QcEpKT2pkMFg2MFNrekRUK0FIVEMySmt2d2ZLcXlmSmlNd25FbzNOUzdjOEhNQnpacXZiNEh6MgpmcXlHdUs2NGozRU9rU2VFWVgvSlNLdVZ1SnNWQ0Rmamd5VUVLWk1laGVKeUhpTWUzZldPelRrcDFCR1pHMDN3CjQvZjVOa1pmQWdNQkFBRUNnZ0VBRkFEQW1VeFRhTHFJcGxqaVh2TGlEOFlZemxtSUJRT0ZScnRlVmlJL1VKMWQKWUxrTkprUW5JUEgyZDdjWE1md3ArUUVXQUpHQVdBZFQ4MlNsY3ovN3VCaEtaWVYvREQrTzZGS05zelhLb0p3QwphaEkrUVc4T1c1NzQ2V1FuUzJ5UTl5MjM1azRaQjlkV0EycVFwK2pXYUJHazJ6ZXRPdEpmRlMyMlRnbUgxMEZMCitMT1A1UFFXQkM0cEx5ZkV6MENkekhpWTIwei9BTmxDOFMwSkZTTDErSlFoMFIwazVnZVJab05LYWJHS20vZ2EKWll2S0RWWHZlczFmUjJGT1A1bDVKYzNiQ3hHSml0VmtBVWIyMGhJbmlYUnc0dkdWUFFaeFZ6R2orUysxRTBrNgpHbVI2QnFpa3dFNDhOcEVuemtsRnVYaG9XVUxHMGE5bzRVU2VJdkJMNFFLQmdRRGdQYlZ5TTU1c0VwaFZMd0dDCnZuNmt4MXJKeEFnR2ZoR1NpanQzK1NtbEJBb0draVB3anRjQU5QMTRabi8vdFdaWDJUb2xvcThleXNZZmxSMkUKb2ludDUzd2pMWnE4eHEvdHk4M3FYRkREREQ1cWVoZlBYUjhNL3JDNm5QNHNtWW5ocEo0TGRIb2xkQTJCSVN1UQpucERZemExOUpPMktOZGpPNkVqNzBIdkhld0tCZ1FETWFvTjBpR2FHWnovT3FoSi9hWklBWkVxcmZqVXNmMFBuCmlmVmhwNVZGcU12WHdpQkc0UDdKdnJKMEk1TXRtNUdFWnpleEhnMzB2RXR2cCtWRWNJKzlzMDNzb3h6dzcwYmkKa3JGb1lmSHBUeDdUVVV5STFCajNMOEJ3Sm0zQXdpTmdQRzFRWHo3RHBsczVNWVgwTVhrSGxlQ3ZVNGtNcWNSagpVUXpEUzh2VmJRS0JnREZLbjBYNVBzdTIwckYyNGJnaHM2ajVBV1gwcDJiMTgxcm84K1dOYWJBU1VUbmNpZlhwCkVDM0ZlQ290TGRuQndEdHpUcXJUTmZkb3oyQkY0UFUweUU2NVlicEIzZys5QlJNYWg2c0ttOTRrSk53MjltRG8Kc1ZpajY2azV0VTJNZXBpVkhRQ2JtL1g3cXJSRjNGT3Y1MXNnNncvbFBDbnphRE1qTUZmYUhqdGRBb0dCQUpsUQpGYkhVRDVra1hSM2lQcWRqQlliWHNZMDN4aWZPZDU1endSOXg4aW5odEtqb3h3NkI5M1pXV1Q5ejR4SGt5Tm9XCkZCWDZKWnQxa2RwM2dTTzRqSVpKc2RzV1owRnBKTEFRTjVERFRRMmdNczFvLzA3c1RLRXdKbE8yN3NBUW16bTEKZUlNOFBEVy9VbEh1QzdxZlZGZlZHRVJIRWRYMmlmMjNMeXhXYjlWdEFvR0JBTDdJN0s5cS9wRzlzTjJoYkV6Vgo4T0YyTDZDMm1UTUlSQlVzQkc1SGUyK1NnTDZzM1owbjk3VVF1YW5KVXJNM0pzS1pzRFVyUndEd09lTHFPQ0Y1Ci9UdTEzNE5seXozR0JETkJZSnpTV2hla1B4VkhtQnZqb0J6WVlTSUdWeVg4SW5WVU41OG9QWVRiS2ZTQ2hPSHMKRjZMRHNrUlU2S3grTnRTYjIzcGZ4MHBnCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4ekNDQXErZ0F3SUJBZ0lVRlhXMWdaNk15QzZydmFJbk5MYnl0MTg4ZU9Jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNTVlF4RHpBTkJnTlZCQWdNQmsxcGJHRnViekVQTUEwR0ExVUVCd3dHVFdscwpZVzV2TVJJd0VBWURWUVFLREFsTmVVTnZiWEJoYm5reExqQXNCZ05WQkFNTUpXRndhUzF6WlhKMmFXTmxMbVJsClptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTk1qVXdOekk0TWpJeE9USXhXaGNOTWpZd056STQKTWpJeE9USXhXakJ6TVFzd0NRWURWUVFHRXdKSlZERVBNQTBHQTFVRUNBd0dUV2xzWVc1dk1ROHdEUVlEVlFRSApEQVpOYVd4aGJtOHhFakFRQmdOVkJBb01DVTE1UTI5dGNHRnVlVEV1TUN3R0ExVUVBd3dsWVhCcExYTmxjblpwClkyVXVaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMTU9lVW5KdGR5V3Vzd3A1RFVsWVJ6ZFNYM1NFVEw4OU5mSnVSZ2Z0UEloWjNyaQorVGRLMUg1aUVsV2ErcTBWaWFzUm9vamROSmlnekRTRVY0MVFZdThmam9vWEFTSWYvK2NQMURETGtYTlhWY04yCkdyUDFqS2g5cWdyT2p1MXdqdnJmU1RKcjNBZDQ2STFnbWsrdW9mN2lBZ2pzWTB4bUt4QVF6L2lJNW9hQTRNMncKbWFQZVd0OFErUmhnajJMYnVEcnR4S2JwMzVubUl3Y3V2T1JCYlNjK2trazZOM1JmclJLVE1OUDRBZE1MWW1TLwpCOHFySjhtSXpDY1NqYzFMdHp3Y3dITm1xOXZnZlBaK3JJYTRycmlQY1E2Uko0UmhmOGxJcTVXNG14VUlOK09ECkpRUXBreDZGNG5JZUl4N2Q5WTdOT1NuVUVaa2JUZkRqOS9rMlJsOENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUUKRktGTUhWSGNyc1VBNkgzaXFLeWhodElFWUwvTU1COEdBMVVkSXdRWU1CYUFGS0ZNSFZIY3JzVUE2SDNpcUt5aApodElFWUwvTU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJeXg0dDdoCldrdHR3TCtLb01pZEMvNG50MkFaMUUxc1MremY5ZFUrMXlYOEtKUWgwYnpLdmIwbEFhTUh6aVpINVV4end6YWkKbURBemRhd3Zud3E4bzhJVUxmT01rZGtxdmI1bHlySm5DM3ZBUW9GcS9qYjdMK3k5a2JxekpYNVVvZUZ5UVgzaApCUDF1cTI4V1ZsQ0pZeWxNM0RGVWVvNzVpbE5MeHY3TmlJYXBBVURXOGFZRGNxcUZOMDJjRUQvdVk4bmtZbk1iCk4xVXlsOEowTWZtejlvQ2hWK3YrTzQvU2F5ZEthK0MxTkp1dkVYRk9RYThsdTRTUDMrYW50cmhZb3EyMytodUwKclQwNkdyOTRvc05YNk1OVlBqdnZLK2dpRHB2T0RsZ0ljS3RObytNS0pZZ21JM2syc3pOMHRDNWVtUGkwdXAyVgpUYzBQbGdBNDRCeFk2eVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.p12: MIIK4gIBAzCCCpgGCSqGSIb3DQEHAaCCCokEggqFMIIKgTCCBNIGCSqGSIb3DQEHBqCCBMMwggS/AgEAMIIEuAYJKoZIhvcNAQcBMFcGCSqGSIb3DQEFDTBKMCkGCSqGSIb3DQEFDDAcBAj8L5h4h3jamgICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEELKA6S9UEZ3JbMQyE3SSj+iAggRQPr2j15YemxJtPIVClGwgMkzkKZAx9G6D6ZmQT/VrsyjBakgHubpBTLrIwl5AMVHodVf03TQDbPtTHOq2HT02n5+jQbwBQqZ3/2XW0UubvOXmnTYLaxGGlM33+wMx4tzcQe9eSj/8yJxhNnpayAHgF7dL1D6HuZ2gFJfeDpql+dmBRyITqMwKmeOMHPsUyT7+cwZyBzhMQ03yFaBbWAsnGGPfsP9M5a/WKvdjiIqRP01JUews81HmWu8JKRyZIrKFuIDG3A9p2wn3t8CN+8NdqwJDYUo56sOcNmGZ8Q2TwRlsVj5A9AqGKoB7vQMz28LjWph9KTwTdoD6UB96UeSZd8GXxX8xHqDXaVCdBLhYQSv0ppwyCN0/+jcs/M0Kek/BK+TyULg1aqp5s02KVIgM/KTshYJvyEewESbMNzD7Yas3pe8jY++Rqsq4oIAUr1q1jhMzMWOus8sXoKkkWAcdFqy7dAn+ZqfI/lZCt/5IwklgM32F5bsRScJRh18O20LVa9w/ofx6E4cnBndB9QaDoA8PHrMYpXDOZ93raeVMVs+QTO6ycD1VTJZjnYmirXEUyTHcmJY1ajjBDKyVpZZu/2eFy57El61PyYWHO021dow1vEPthGqiD1TcEbOiW1uGmoX8n/s3yiK3YPGAIdnUYheYsavuJsjQpyufMqr0T4J6Uj0pnR/tHjOjdukceoN82iMqtTg8tyGqlR07kCGN7NM6S6ZnTBP1rTAG+AE4aJqNKLZwMruKPwRw10s4c/po4p3BtVkKZ0DwWhJ1CEJHRqnfxSeVraHIq+SD2821Hdtdmd/HSFRk0n+jzbdQ/12x3Z3zU0AAcgGAKLTpxm0+9FkGkUZvseRhWmAC5EpEh1F4vynrM+oOC3BPOAoOG6cqgbk2Co//1l2qPWZGjqQwvT9ZVisOgpR7S64hPyhXgSJJDbpN5ZWrhwzfQvzflZdYVO7ixx15E0+DsMVdBxopbNI2Y26mrkHTV/OrJNeTJH+3JznHWitT6QjlWhuzFsi3l1ypr3JXuXoNEzDVwbOeJb/W8fy8BLKNTCx3ldPa/RMdww3tWA7WpoEZWIUqlnhgt/5CbHMHg5aO2ZvAeMZLpYL1cXLzdQWLtBnCT/A0lpGkJ6UXnIjVsfDsCdS+PW5b1VLgIm7SCten1fYdiPYtoiG+McgPlw54/IER7ildn0u+55ve/gHirZ4k+4fa33OFlHTQODXkl0MUxiE/fqEOjB/i51CBM1kNvicd5WpZFAk+Zl36HmfJSU4QGHmlgCEu+jFg+o6r0Uq3hiOhTyC458zaB1zqc90NC42tm2sP6kNe9h0FWZ0hlBU8l3Ho+mHETr6K5eBJ/POieAVj5gz2xl/JFyOIkDepegavqZ0RLKy8NJqqDYCi1FQMKb7CxGnRBqPlQhfvWSFQUoql+UNQxdwqMk2kkM+9uGx39yu+BdePyMtAgnBY6P0IzjDRTQ42MIIFpwYJKoZIhvcNAQcBoIIFmASCBZQwggWQMIIFjAYLKoZIhvcNAQwKAQKgggUxMIIFLTBXBgkqhkiG9w0BBQ0wSjApBgkqhkiG9w0BBQwwHAQI44TbIih+ukwCAggAMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBAifL+fzcPyAHRIEg01bIYDBIIE0I8pLVvI1Rkb2VkiW70f24voShc6D6453qSTnq7yHahUCfCdF79eQIzxhWKdjj/WiSOarEwK+FY7W522gd8I86S/kZyJvdXb1L8GjmglvK9kwnirmb8xG79uJG5wpaA3aUI/1hmLZe82LsGllEEqWGKDvF5jfcDWHPpBR1eeTJOWiqCOksNnCya3QQmm66BnajNlK85rFs8XDQmd7h4EnvnE1aI+teTmhTbX4dd3RJGRnzL2SteDEg9CmvO3v/QTRjFnW7imkVdElS7OZfcDDlPYX+j+V00Slcz8U9tkwQmCELhZ9WnxYu1SvCnMLH5g4IXNKRhmj7YF5/VxpSkiWo69muIu5LooPTPRzBu8DQp421758jfG1MND+7rq6zk5rRPbFE6dzpyWHxmbzwW2N7isfsYPOPfxxlGEElSA+3EEIYZrRiS8bsFO4gzDaqeqUk5ScRBPiC6f2L6Q0+HObu90bARlYwuxASQm0HbYPlgcXO/ddPTpB1qurSpDtQ5ZFMxCsqSvDp9NLTE4+GFn1FS0LbFuvojEzOVivQJX2Sfis8NZHuaYun0A0kyL3hZFxJgC6Qh7nOEtC30ip6Qn33VC752aQvCTm+IJnMEF8WBqwG+ktNZnEnQGyXeJsWKtUHyVNexXiLr8STeqvrQbpd3rZLQWb5Y9yM324rM7833kx5pw/rKrCaXsQiH037ey36NfYN8+qqSqiMPLCqouk1LsFssQQUmS/lUDFdnVdn0KmqYoZSLSv8b8GyCHddYvs5e2gGySuEAGuJZWCHFD/XFflEO+2PzG+p0c7DyR5Dsx8RYY4d+FW8K5TSZvtd/EVRmtFJ+yqpA91GxMI2AnBeQXMTv1iEw+98p6HUtnv5BaTOGLOFeTd/b/VQ4UyaGKrOKH+z2feKfi0rWAugMJDYmKF72lRSsSQTnll/fV2R6la7kJyGDLhgG9PHFcauwtqqi3Lht0xRmr12qFVBTeAMuYsHLVi/vx/5wD5b1iwXFzaWKZbdHzdpNXfICjlZKfGgpz23FUfHs2FH8tdJfEXWQPvhXiHB6prdSYARILzxQl1Se3B9bUuVNPO3sNTDNCt8Y2+jzIr5jxbONF+IPTHpYKUCShv2zyXmAsI5z8De9bRHd4JjdTPD+Egb03QWyskRiV+kyxe2jv6qMpHxkc41kwe/p0FwlDsTCzLBkwIv+DNN6p0c6azId8OpX5zApXFIEwvNlRPtjg2tgYwpAvNQtkpuc9DB7MWLtEagVLPfy8AhldOwoydPbntUgarAut3XCtUKWShAWd3bSPMQFUVB3tFc4UeVv2jCN8uch/ty3feAjBpzNmOiwRoaXj9oETmPA4gDvb621ywvLtvUD5qPDzdJ1sAG7lJHfU1vwRdLUV5Yiqw0atSPED2OScmx/R9IZhXd55UDGysWvfyus0DY+KDm4Iea/8TkxTLV5doDU4FcNVAaWp8sGlBgAno+HzMmJKdWazNPBcqFC+xhhZwJxUUi/iMREFdG6FU5s/6cFYJ3qL3B5txNzMncJYvTKvoDWAqkO+pYgE50ZGpZNT1OlApMIX8orv4Ju6z7xaPg7MDL7lzfDkJV/2fnepR3zLRNxLzf8i6+ycCC2+k49nTCAHYO/ujCqQQHleszb1U13kMUgwIQYJKoZIhvcNAQkUMRQeEgB0AGwAcwAtAGEAbABpAGEAczAjBgkqhkiG9w0BCRUxFgQUZiRV6TrEcz3l5b9rJABSl/Nz/qcwQTAxMA0GCWCGSAFlAwQCAQUABCAQ4ArHMKN42kNu81xaJeOdojQOCwqkIOPa/yJnARIkUAQIZOTT4GFLpS8CAggA
---

# Se si desisdera un .p12 bisognerà creare un nuovo Secret che contenga 
# la password per il file PKCS12. 
# Questo Secret deve essere referenziato in passwordSecretRef nel Certificate.

apiVersion: v1
kind: Secret
metadata:
  name: api-service-tls-password
  namespace: default
type: Opaque
stringData:
  # Sostituisci con una password sicura per il tuo ambiente di produzione
  # password: "changeit" in base64
  # echo -n "changeit" | base64
  password: changeit
  # password: "changeit"
  
---

# Questo Issuer crea certificati self-signed. 

# Per un ambiente di produzione, 
# si potrebbe usare un ClusterIssuer con ACME (Let's Encrypt).

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  # Assicurati che sia nello stesso namespace dei tuoi pod
  namespace: default 
spec:
  #selfSigned: {}
  ca:
    secretName: java-ca-secret

---


# Questo Certificate indica a Cert-Manager di creare un certificato 
# per il servizio api-service e di salvarlo come Secret di tipo tls. 

# Il dnsNames deve corrispondere al nome del servizio 
# Kubernetes (api-service.default.svc.cluster.local).

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-service-tls
  namespace: default
spec:
  secretName: api-service-tls-secret # Il nome del Secret che conterrà il certificato e la chiave
  # duration: 2160h # 90d
  # renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: api-service.default.svc.cluster.local 
  dnsNames:
    - api-service.default.svc.cluster.local  
  # # Questa sezione per la generazione del keystore PKCS12 se si intende utilizzare un .p12
  # keystores:
  #   pkcs12:
  #     create: true
  #     # password: changeit
  #     passwordSecretRef:
  #       # Nome del Secret che contiene la password per il .p12
  #       name: api-service-tls-password 
  #       # Chiave all'interno del Secret che contiene la password
  #       key: password 

---

# # Questa ConfigMap passa l'URL del servizio API al client
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: client-config
#   namespace: default
# data:
#   api.url: "https://api-service.default.svc.cluster.local:8443" # URL del servizio API all'interno del cluster

