apiVersion: v1
kind: Pod
metadata: 
  name: downwardapi-demo-pod
  labels:
    app: downwardapi-demo-app
    env: dev
  annotations:
    description: "Esempio di utilizzo di un Downward API"
spec:
  containers:
    - name: main-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - | 
          echo "POD_NAME=${POD_NAME}";
          echo "POD_NAMESPACE=${POD_NAMESPACE}";
          echo "Label lette da file:";
          cat /etc/pdoinfo/labels;
          sleep infinity;
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valuefrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: podinfo
          mountPath: /etc/pdoinfo/
          readOnly: true
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "containers"
            fieldRef:
              fieldPath: spec.containers
